version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          key: v1-shenfun-{{ .Branch }}

      - run:
          name: install miniconda
          command: |
            cd /home/circleci
            echo 'export MINICONDA=$HOME/miniconda' >> ~/.bashrc
            echo 'export PATH="$MINICONDA/bin:$PATH"' >> ~/.bashrc
            source ~/.bashrc
            hash -r
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -f -p $MINICONDA
            conda config --set always_yes yes
            conda update -q conda
            conda config --add channels conda-forge
            conda config --add channels spectralDNS
            conda install -n root conda-build
            conda install --yes --quiet conda-forge-build-setup
            source run_conda_forge_build_setup

      - save_cache:
          key: v1-shenfun-{{ .Branch }}
          paths:
            - ~/shenfun

      - run:
          name: Build and test
          command: |
            source ~/miniconda/bin/activate root
            cd /home/circleci/project
            conda build ./conf/conda
            conda build --python 3.6 ./conf/conda
        
      - run:
          name: Upload packages
          command: |
              source ~/.bashrc
              source ~/miniconda/bin/activate root
              cd /home/circleci/project
              upload_or_check_non_existence ./conf/conda spectralDNS --channel main
              export CONDA_PY=36
              upload_or_check_non_existence ./conf/conda spectralDNS --channel main

