package:
  name: shenfun
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../../

build:
  number: 3

requirements:
  build:
    - numpy >=1.16
    - setuptools
    - python
    - cython
    - mpi4py
    - mpi4py-fft >=1.1.1
    - mpich
    - pip
    - fftw
    - nomkl
    - scipy

  run:
    - python
    - numpy >=1.16
    - scipy
    - cython
    - fftw
    - mpi4py
    - mpi4py-fft >=1.1.1
    - mpich
    - sympy
    - nomkl
    - hdf5-parallel
    - netcdf4-parallel

test:
  source_files:
    - tests
    - demo

  imports:
    - shenfun

  requires:
    - pytest
