{% if GIT_DESCRIBE_TAG is defined %}
{%   set version = GIT_DESCRIBE_TAG %}
{% else %}
{%   set version = "1.0" %}
{% endif %}

package:
  name: shenfun
  version: version

source:
  git_url: ../../
  #url: https://pypi.io/packages/source/s/shenfun/shenfun-{{ version }}.tar.gz

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - setuptools
    - cython
    - pip
    - fftw

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - fftw
    - mpi4py
    - mpi4py-fft >=2.0.3
    - sympy
    - {{ mpi }}
    - h5py * mpi_{{ mpi }}_*
    - netcdf4 * mpi_{{ mpi }}_*

test:
  source_files:
    - tests
    - demo

  imports:
    - shenfun

  requires:
    - pip
    - pytest
