package:
  name: shenfun
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../../
  url: https://pypi.io/packages/source/s/shenfun/shenfun-{{ version }}.tar.gz

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - numpy
    - setuptools
    - cython
    - pip
    - fftw
    - nomkl

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - fftw
    - mpi4py
    - mpi4py-fft
    - sympy
    - nomkl
    - hdf5 * mpi_*
    - h5py * mpi_*
    - netcdf4-parallel

test:
  source_files:
    - tests
    - demo

  imports:
    - shenfun

  requires:
    - pytest
