package:
  name: shenfun
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../../

build:
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - pip
    - fftw
    - nomkl
    - scipy

  run:
    - python
    - numpy
    - scipy
    - cython
    - fftw
    - mpi4py
    - sympy
    - nomkl
    - h5py-parallel
    - netcdf4-parallel

test:
  source_files:
    - tests
    - demo

  imports:
    - shenfun

  requires:
    - pytest
