package:
  name: shenfun
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  git_url: ../../

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - numpy >=1.16
    - setuptools
    - python
    - cython
    - mpi4py
    - mpi4py-fft >=1.1.2
    - {{ mpi }}
    - pip
    - fftw
    - nomkl
    - scipy

  run:
    - python
    - numpy >=1.16
    - scipy
    - fftw
    - mpi4py
    - mpi4py-fft >=1.1.2
    - {{ mpi }}
    - sympy
    - nomkl
    - hdf5 1.10.4 mpi_{{ mpi }}_*
    - h5py * mpi_{{ mpi }}_*
    - netcdf4-parallel

test:
  source_files:
    - tests
    - demo

  imports:
    - shenfun

  requires:
    - pytest
