package:
  name: shenfun
  version: "1.1.0"

source:
  git_url: ../../

build:
  number: 7

requirements:
  build:
    - python
    - cython
    - numpy
    - pip
    - fftw
    - nomkl

  run:
    - python
    - numpy
    - scipy
    - cython
    - pyfftw
    - mpi4py
    - six
    - sympy
    - nomkl
    - h5py-parallel
    - libnetcdf-parallel
    - netcdf4-parallel

test:
  source_files:
    - tests
    - demo

  imports:
    - shenfun

  requires:
    - pytest
