name: shenfun_doc_env

channels:
  - spectralDNS
  - defaults
  #- conda-forge

dependencies:
  - python=3.6
  - anaconda
  - cython
  - fftw
  - numpy
  - sympy
  - python
  - scipy
  #- doconce
  - pyfftw
  - mpiFFT4py
  - mpi4py_fft
  - pip:
    - sphinxcontrib-bibtex

