name: shenfun_doc_env

channels:
  - spectralDNS
  - defaults

dependencies:
  - python=3.6
  - cython
  - fftw
  - numpy
  - sympy
  - python
  - scipy
  - mpi4py-fft
  - pip:
    - sphinxcontrib-bibtex
