name: shenfun_doc_env

channels:
  - conda-forge
  - spectralDNS

dependencies:
  - cython
  - fftw
  - numpy
  - sympy
  - python
  - scipy
  - dask
  - doconce
  - pyfftw
  - mpiFFT4py
  - mpi4py_fft
  - sphinxcontrib-bibtex

