name: shenfun_doc_env

channels:
  - defaults

dependencies:
  - python=3.7
  - cython
  - fftw
  - numpy=1.16
  - nomkl
  - sympy
  - scipy
  - mpi4py
  - mpi4py-fft
  - pip:
    - sphinxcontrib-bibtex
