name: shenfun_doc_env

channels:
  - defaults

dependencies:
  - python=3.6
  - cython
  - fftw
  - numpy 1.16.*
  - nomkl
  - sympy
  - python
  - scipy
  - mpi4py
  - pip:
    - mpi4py-fft
    - sphinxcontrib-bibtex
