name: github-CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.9", "3.10"]
    name: Python ${{ matrix.python-version }} example

    steps:
    - uses: actions/checkout@v3
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: setup-conda
      uses: s-weigand/setup-conda@v1
      with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python
    - run: |
        conda config --set always_yes yes
        conda install -n root conda-build numpy
        conda build ./conf/conda

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        name: codecov-shenfun
        verbose: true
